DiaryApp/Models/DiaryEntry.cs
using System.ComponentModel.DataAnnotations;

namespace DiaryApp.Models
{
    public class DiaryEntry
    {
        // Properties for the DiaryEntry class
        public int Id { get; set; }

        [Required(ErrorMessage ="Please Enter a Title")]
        [StringLength(50, MinimumLength = 2,
            ErrorMessage ="The title must be between 2 and 50 Characters")]
        public required string Title { get; set; }
        [Required(ErrorMessage ="Please Enter a Description")]
        public required string Description { get; set; }
        [Required(ErrorMessage ="Please Enter the Date it was Created")]
        public DateTime CreatedAt { get; set; } = DateTime.Now;
    }
}

DiaryApp/Models/ErrorViewModel.cs
namespace DiaryApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DiaryApp/Controllers/DiaryEntriesController.cs
using DiaryApp.Data;
using DiaryApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace DiaryApp.Controllers
{
    public class DiaryEntriesController : Controller
    {
        private readonly ApplicationDbContext _db;

        public DiaryEntriesController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            List<DiaryEntry> diaryEntries = _db.DiaryEntries.ToList();


            return View(diaryEntries);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(DiaryEntry obj)
        {
            if (obj != null && obj.Title.Length < 3)
            {
                ModelState.AddModelError("Title", "The title is too short.");
            }
            if (ModelState.IsValid)
            {
                _db.DiaryEntries.Add(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            DiaryEntry? diaryEntry = _db.DiaryEntries.Find(id);
            if (diaryEntry == null)
            {
                return NotFound();
            }
            return View(diaryEntry);
        }

        [HttpPost]
        public IActionResult Edit(DiaryEntry obj)
        {
            if (obj != null && obj.Title.Length < 3)
            {
                ModelState.AddModelError("Title", "The title is too short.");
            }
            if (ModelState.IsValid)
            {
                _db.DiaryEntries.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            DiaryEntry? diaryEntry = _db.DiaryEntries.Find(id);
            if (diaryEntry == null)
            {
                return NotFound();
            }
            return View(diaryEntry);
        }

        [HttpPost]
        public IActionResult Delete(DiaryEntry obj)
        {
            if (obj != null)
            {
                _db.DiaryEntries.Remove(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }
    }
}

DiaryApp/Controllers/HomeController.cs
using System.Diagnostics;
using DiaryApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace DiaryApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        public IActionResult MyPage()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DiaryApp/Views/DiaryEntries/Create.cshtml
@model DiaryEntry

<div class="container mt-4">
	<div class="row">
		<div class="col-md-8 offset-md-2">
			<div class ="card">
				<div class="card-header bg-primary text-white">
					<h2>Create Diary Entry</h2>
				</div>
				<div class="card-body">
					<form asp-action="Create" method="post">
						<div asp-validation-summary="All" class="text-danger"></div>
						<div class="form-group mb-3">
							<label asp-for="Title" class="form-label">Title</label>
							<input asp-for="Title" class="form-control" placeholder="Enter a title"/>
							<span asp-validation-for="Title" class="text-danger"></span>
						</div>
						<div class="form-group mb-3">
							<label asp-for="Description" class="form-label">Description</label>
							<input asp-for="Description" row:"5" class="form-control" placeholder="Enter the activities you did that day" />
							<span asp-validation-for="Description" class="text-danger"></span>
						</div>
						<div class="form-group mb-3">
							<label asp-for="CreatedAt" class="form-label">Created At</label>
							<input asp-for="CreatedAt" type="date" class="form-control" />
							<span asp-validation-for="CreatedAt" class="text-danger"> </span>
						</div>
						<div class="d-flex justify-content-between">
							<button type="submit" class="btn btn-primary">Create</button>
							<a class="btn btn-danger" asp-action="Index">Cancel</a>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

@section Scripts {
	<partial name="_ValidationScriptsPartial" />
}

DiaryApp/Views/DiaryEntries/Delete.cshtml
@model DiaryEntry

<div class="container mt-4">
	<div class="row">
		<div class="col-md-8 offset-md-2">
			<div class="card">
				<div class="card-header bg-primary text-white">
					<h2>Delete Diary Entry</h2>
				</div>
				<div class="card-body">
					<form asp-action="Delete" method="post">
						<div asp-validation-summary="All" class="text-danger"></div>
						<div class="form-group mb-3">
							<label asp-for="Title" class="form-label">Title</label>
							<input asp-for="Title" class="form-control" placeholder="Enter a title" />
							<span asp-validation-for="Title" class="text-danger"></span>
						</div>
						<div class="form-group mb-3">
							<label asp-for="Description" class="form-label">Description</label>
							<input asp-for="Description" row:"5" class="form-control" placeholder="Enter the activities you did that day" />
							<span asp-validation-for="Description" class="text-danger"></span>
						</div>
						<div class="form-group mb-3">
							<label asp-for="CreatedAt" class="form-label">Created At</label>
							<input asp-for="CreatedAt" type="date" class="form-control" />
							<span asp-validation-for="CreatedAt" class="text-danger"> </span>
						</div>
						<div class="d-flex justify-content-between">
							<button type="submit" class="btn btn-danger">Delete</button>
							<a class="btn btn-secondary" asp-action="Index">Cancel</a>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

@section Scripts {
	<partial name="_ValidationScriptsPartial" />
}

DiaryApp/Views/DiaryEntries/Edit.cshtml
@model DiaryEntry

<div class="container mt-4">
	<div class="row">
		<div class="col-md-8 offset-md-2">
			<div class="card">
				<div class="card-header bg-primary text-white">
					<h2>Edit Diary Entry</h2>
				</div>
				<div class="card-body">
					<form asp-action="Edit" method="post">
						<div asp-validation-summary="All" class="text-danger"></div>
						<div class="form-group mb-3">
							<label asp-for="Title" class="form-label">Title</label>
							<input asp-for="Title" class="form-control" placeholder="Enter a title" />
							<span asp-validation-for="Title" class="text-danger"></span>
						</div>
						<div class="form-group mb-3">
							<label asp-for="Description" class="form-label">Description</label>
							<input asp-for="Description" row:"5" class="form-control" placeholder="Enter the activities you did that day" />
							<span asp-validation-for="Description" class="text-danger"></span>
						</div>
						<div class="form-group mb-3">
							<label asp-for="CreatedAt" class="form-label">Created At</label>
							<input asp-for="CreatedAt" type="date" class="form-control" />
							<span asp-validation-for="CreatedAt" class="text-danger"> </span>
						</div>
						<div class="d-flex justify-content-between">
							<button type="submit" class="btn btn-primary">Edit</button>
							<a class="btn btn-danger" asp-action="Index">Cancel</a>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>

@section Scripts {
	<partial name="_ValidationScriptsPartial" />
}

DiaryApp/Views/DiaryEntries/Index.cshtml
@model List<DiaryEntry>

<div class="container">
	<div class="row pt-4">
		<div class="col-6">
			<h2>Diary Entries</h2>
		</div>
		<div class="col-6 text-end">
			<a class="btn btn-primary"  asp-action="Create">
				Create New Diary Entry
			</a>
		</div>
	</div>
</div>

<div class="table-responsive">
	<table class="table table-striped table-hover">
		<thead>
			<tr>
				<th>Title</th>
				<th>Description</th>
				<th>Created At</th>
				<th>Actions</th>
			</tr>
		</thead>
		<tbody>
			@foreach(var entry in Model)
			{
				<tr>
					<td>@entry.Title</td>
					<td>@entry.Description</td>
					<td>@entry.CreatedAt.ToString("g")</td>
					<td>
						<a asp-controller="DiaryEntries" asp-action="Edit" asp-route-id="@entry.Id" class="btn btn-primary btn-sm">
							Edit
						</a>
						<a asp-controller="DiaryEntries" asp-action="Delete" asp-route-id="@entry.Id" class="btn btn-danger btn-sm">
							Delete
						</a>
					</td>
					
				</tr>
			}
		</tbody>
	</table>
</div>

DiaryApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

DiaryApp/Views/Home/MyPage.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>Welcome to My Page!</h1>

DiaryApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DiaryApp</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/DiaryApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-light" asp-area="" asp-controller="Home" asp-action="Index">
                    My Diary 
                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-journal-text" viewBox="0 0 16 16">
                        <path d="M5 10.5a.5.5 0 0 1 .5-.5h2a.5.5 0 0 1 0 1h-2a.5.5 0 0 1-.5-.5m0-2a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5m0-2a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5m0-2a.5.5 0 0 1 .5-.5h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1-.5-.5" />
                        <path d="M3 0h10a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2v-1h1v1a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H3a1 1 0 0 0-1 1v1H1V2a2 2 0 0 1 2-2" />
                        <path d="M1 5v-.5a.5.5 0 0 1 1 0V5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1zm0 3v-.5a.5.5 0 0 1 1 0V8h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1zm0 3v-.5a.5.5 0 0 1 1 0v.5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1z" />
                    </svg>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-light" asp-area="" asp-controller="DiaryEntries" asp-action="Index">Diaries</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - DiaryApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>